<div class="span12" file="tab1.phtml" widget-class="AdminSMPane" widget-id="admin-sm-man-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>短信报警管理</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">

                    <li class=""><a href="#alert_freq_tab" data-toggle="tab" tab="man">报警时间</a></li>

					<li class="active"><a href="#add_phone_tab" data-toggle="tab" tab="add">用户管理</a></li>

				</ul>
				<div class="tab-content">
					<div class="tab-pane" id="alert_freq_tab">
						<div >
                            <span>短信报警间隔:</span><input type="text" value="4" id="alert-hour-set-input" /><span>小时</span>
                            <a class="btn blue set-freq">设置</a>
                        </div>
					</div>

					<div class="tab-pane active" id="add_phone_tab">
                        <span style="font-weight: bold">管理手机号码</span>
                        <div class="users" style="max-width: 400px"></div>

                        <span style="font-weight: bold">添加新手机号码</span>

                        <table style="margin-top: 10px">
                            <tr>
                                <td>姓名</td><td><input class="name" type="text"/></td>
                            </tr>
                            <tr>
                                <td>手机号码</td><td><input class="phone" type="text"/></td>
                            </tr>

                            <tr>
                                <td></td>
                                <td>
                                    <a class="btn add-admin blue">添加</a>
                                </td>
                            </tr>
                        </table>

					</div>


				</div>
			</div>
		</div>
	</div>
</div>
