<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="cinderella-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;特征核素甄别系统</i></div>
		</div>
        <div class="portlet-body" widget-class="CinderellaDevice" widget-id="cinderella-device">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="#cinderella_history" data-toggle="tab" class="history">获取率</a></li>
                    <li><a href="#cinderella_sum" data-toggle="tab" class="summary">统计</a></li>
                    <li><a href="#cinderella_config" data-toggle="tab">设置</a></li>
                    <li class="'dropdown">
                        <a id="cinderella_alert_a" href="#cinderella_alert" data-toggle="tab" class="dropdown-toggle alerts" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li><a href="#cinderella_chart" class="charts" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#cinderella_data" data-toggle="tab">数据</a></li>
                </ul>
                <div class="tab-content" style="position:relative;">

                    <div class="tab-pane active" id="cinderella_data">
                        <!--
                        <div class="interval">
                            <a class="btn red s30">30秒</a><a class="btn m5">5分钟</a><a class="btn h1">1小时</a>
                        </div>
                        -->
                        <div class="refresh-bar" style="position:absolute;display: none; height: 24px;width: 100%; top:0px;left:0px;background-color: cornsilk">
                            <a href="javascript:void(0)"><span>点击获取最新数据</span></a>
                        </div>
                        <div class="data-pane">

                        </div>
                    </div>

                    <div class="tab-pane" id="cinderella_chart">
                        <div class="chart-interval">
                            <a class="btn  s30">30秒</a><a class="btn red m5">5分钟</a><a class="btn h1">1小时</a>
                        </div>
                        <div class="charts">

                        </div>
                        <div class="charts-bar" style="height: 80px">

                        </div>
                    </div>

                    <div class="tab-pane config" id="cinderella_config">
                    </div>

                    <div class="tab-pane" id="cinderella_alert">
                        <div class="alert-pane">

                        </div>
                    </div>

                    <div class="tab-pane" id="cinderella_sum">
                        <div class="sum-container">
                        </div>
                        <div class="pagebar2"></div>
                    </div>

                    <div class="tab-pane" id="cinderella_history">
                        <div class="calendar-container" class="fc-ltr fc">
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
