<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="mds-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;大体积放射源搜索系统</i></div>
		</div>
		<div class="portlet-body" widget-class="MdsDevice" widget-id="mds-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <!--
                    <li><a href="#mds_history" data-toggle="tab" class="history">获取率</a></li>
                    -->
                    <li><a href="#mds_config" data-toggle="tab">设置</a></li>
                    <li class="'dropdown">
                        <a id="mds_alert_a" href="#mds_alert" data-toggle="tab" class="dropdown-toggle alerts" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li class=""><a href="#mds_chart" class="charts" data-toggle="tab">曲线</a></li>
                    <li class=""><a href="#mds_statisic" class="summary" data-toggle="tab">统计</a></li>
                    <li class="active"><a href="#mds_data" data-toggle="tab">数据</a></li>

				</ul>
				<div class="tab-content">

                    <div class="tab-pane active" id="mds_data">
                        <div class="data-pane">

                        </div>
                    </div>
                    <div class="tab-pane" id="mds_statisic">
                        <div class="sum-container">

                        </div>

                        <div class="gis" style="display: none">
                            <a class="btn blue">返回</a>
                            <div >

                            </div>
                        </div>
                    </div>

                    <div class="tab-pane" id="mds_chart">
                        <div class="chart-interval">
                            <select class="chart-field" style="margin-top: 10px">
                                <option value="doserate" max="55" min="-20">剂量率</option>
                                <option value="doserateex" max="1200" min="900">剂量率EX</option>
                            </select>
                            <a class="btn  s30">30秒</a><a class="btn red m5">5分钟</a><a class="btn h1">1小时</a>
                        </div>
                        <div class="charts">

                        </div>
                        <div class="charts-bar" style="height: 80px">

                        </div>
                    </div>

                    <div class="tab-pane" id="mds_alert">
                        <div class="alert-pane">

                        </div>
                    </div>

                    <div class="tab-pane config" id="mds_config">
                    </div>

                    <!--
                    <div class="tab-pane" id="mds_history">
                        <div class="calendar-container" class="fc-ltr fc">
                        </div>
                    </div>
                    -->
                </div>
			</div>
		</div>
	</div>
</div>
