<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="labr-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;Labr谱仪</i></div>
		</div>
        <div class="portlet-body" widget-class="LabrDevice" widget-id="labr-device">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="#labr_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#labr_data" data-toggle="tab">数据</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="labr_data">

                    </div>

                    <div class="tab-pane active" id="labr_chart">
                    </div>

                </div>
            </div>
        </div>
	</div>
</div>
