<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="cinderella-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;特征核素甄别系统</i></div>
		</div>
        <div class="portlet-body" widget-class="CinderellaDevice" widget-id="cinderella-device">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="#cinderella_alert" data-toggle="tab">报警</a></li>
                    <li><a href="#cinderella_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#cinderella_data" data-toggle="tab">数据</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="cinderella_data">
                        <div class="list-pane"></div>
                    </div>

                    <div class="tab-pane" id="cinderella_chart">
                    </div>

                    <div class="tab-pane" id="cinderella_alert">
                    </div>

                </div>
            </div>
        </div>
	</div>
</div>
