<div class="row-fluid">
    <!-- Cinderella -->
    <div class="span3" >
        <div class="portlet box blue tabbable" widget-class="CinderellaSummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">

                    <div class="tab-content">

                        <div class="active" id="cinderella_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                                <br>
                                <span class="label mode "></span>
                                <br>
                                <span class="label loop "></span>
                                <br>
                                <span class="label step "></span>
                            </div>

                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="span3" file="tab1.phtml">
        <div class="portlet box blue tabbable" widget-class="HpgeSummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">

                    <div class="tab-content">

                        <div class=" active" id="hpge_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>

                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- HPIC -->
    <div class="span3" file="tab1.phtml">
        <div class="portlet box blue tabbable" widget-class="HpicSummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">

                    <div class="tab-content">
                        <div class=" active" id="hpic_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!------------------------------- Line 2 --------------------------------->
<div class="row-fluid">


    <div class="span3" file="tab1.phtml">
        <div class="portlet box blue tabbable" widget-class="Bai9850SummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder">Bai9850</i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">

                    <div class="tab-content">

                        <div class=" active" id="bai9850_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- 环境与安防监控 -->
    <div class="span3" file="tab1.phtml">
        <div class="portlet box blue tabbable" widget-class="EnvSummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">

                    <div class="tab-content">
                        <div class=" active" id="env_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="span3" file="tab1.phtml">
        <div class="portlet box blue tabbable" widget-class="WeatherSummaryDevice">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder">气象</i></div>
            </div>
            <div class="portlet-body" widget-class="">
                <div class="">
                    <div class="tab-content">
                        <div class=" active" id="weather_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>
<!------------------------------- Line 3--------------------------------->
<!--
<div class="row-fluid">
        <div class="span4" file="tab1.phtml">
            <div class="portlet box blue tabbable" widget-class="LabrFilterSummaryDevice">
                <div class="portlet-title">
                    <div class="caption"><i class="icon-reorder"></i></div>
                </div>
                <div class="portlet-body" widget-class="">
                    <div class="">

                        <div class="tab-content">

                            <div class=" active" id="labrfilter_devices">
                                <div class=" active" id="hpge_devices">
                                    <div class="panel">
                                        <span class="label run label-success"></span>
                                    </div>
                                    <a href="#" class="btn green details">查看详情 <i class="m-icon-swapright m-icon-white"></i></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="clearfix"></div>
</div>
-->
