<div class="row-fluid">
<!-- Cinderella -->
<div class="span4" file="tab1.phtml">
    <div class="portlet box blue" widget-class="GamaSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class="active" id="cinderella_devices">
                        <div class="panel">
                            <span class="label run label-success"></span>
                        </div>

                        <a href="#" class="btn green details">查看详情</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="HpGeSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class=" active" id="hpge_devices">
                        <div class="panel">
                            <span class="label run label-success"></span>
                        </div>

                        <a href="#" class="btn green details">查看详情</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="LabrSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class=" active" id="labr_devices">
                        <div class=" active" id="hpge_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情</a>
                        </div>
                    </div>

                    <!--
                    <div class="" id="labr_settings">
                        <a href="#" class="btn green change-alert">确定</a>
                    </div>
                    -->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
</div>
