<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="bai9850-tab-pane">
    <div class="portlet box blue tabbable">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">&nbsp;气溶胶总放与碘自动监测系统</i></div>
        </div>
        <div class="portlet-body" widget-class="Bai9850Device" widget-id="bai9850-device">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="#bai9850_history" data-toggle="tab" class="history">获取率</a></li>
                    <li><a href="#bai9850_config" data-toggle="tab" class="config">设置</a></li>
                    <li class="'dropdown">
                        <a id="bai9850_alert_a" href="#bai9850_alert" data-toggle="tab" class="dropdown-toggle alerts" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li class=""><a href="#bai9850_chart" class="charts" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#bai9850_data" data-toggle="tab">数据</a></li>

                </ul>
                <div class="tab-content" style="position:relative;">

                    <div class="tab-pane active" id="bai9850_data">
                        <div class="refresh-bar" style="position:absolute;display: none; height: 24px;width: 100%; top:0px;left:0px;background-color: cornsilk">
                            <a href="javascript:void(0)"><span>点击获取最新数据</span></a>
                        </div>
                        <div class="data-pane">

                        </div>
                    </div>


                    <div class="tab-pane" id="bai9850_chart">
                        <div class="chart-interval">
                            <select class="chart-field" style="margin-top: 10px">
                                <option value="alphaactivity" max="55" min="-20">α活度</option>
                                <option value="alpha" max="1200" min="900">α</option>
                                <option value="betaactivity" max="100" min="0" >β活度</option>
                                <option value="beta" max="100" min="0" >β</option>
                                <option value="i131activity" max="100" min="0" >碘131活度</option>
                                <option value="i131" max="100" min="0" >碘131</option>
                                <option value="doserate" max="100" min="0" >相对剂量率</option>
                            </select>
                            <a class="btn  s30">30秒</a><a class="btn red m5">5分钟</a><a class="btn h1">1小时</a>
                        </div>
                        <div class="charts">

                        </div>
                        <div class="charts-bar" style="height: 80px">

                        </div>
                    </div>

                    <div class="tab-pane" id="bai9850_alert">
                        <div class="alert-pane">

                        </div>
                    </div>

                    <div class="tab-pane config" id="bai9850_config">
                        <div class="configAlert-pane">

                        </div>
                    </div>

                    <div class="tab-pane" id="bai9850_history">
                        <div class="calendar-container" class="fc-ltr fc">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>