<div class="span12" file="tab1.phtml" widget-class="NetworkTabPane" widget-id="network-tab-pane">
	<div class="portlet box green tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;监测网络</i></div>
		</div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#stations" data-toggle="tab">自动站</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="stations">
                        <div class="list-pane"></div>
                    </div>


                </div>
            </div>
        </div>
	</div>
</div>
