<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="environment-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;环境与安防</i></div>
		</div>
		<div class="portlet-body" widget-class="EnvironmentDevice" widget-id="environment-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#weather_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#weather_data" data-toggle="tab">数据</a></li>
				</ul>
				<div class="tab-content">

                    <div class="tab-pane active" id="weather_data">
                    </div>
					<div class="tab-pane" id="weather_chart">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
