<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="labr-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;溴化镧能谱仪</i></div>
		</div>
        <div class="portlet-body" widget-class="LabrDevice" widget-id="labr-device">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="#labr_config" data-toggle="tab">设置</a></li>
                    <li class="'dropdown">
                        <a id="labr_alert_a" href="#labr_alert" data-toggle="tab" class="dropdown-toggle alerts" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li><a href="#labr_chart" class="charts" data-toggle="tab">曲线</a></li>
                    <li><a href="#labr_chart_energy" class="charts-energy" data-toggle="tab">能谱图</a></li>
                    <li class="active"><a href="#labr_data" data-toggle="tab">数据</a></li>
                </ul>
                <div class="tab-content" style="position:relative;">

                    <div class="tab-pane active" id="labr_data">
                        <div class="refresh-bar" style="position:absolute;display: none; height: 24px;width: 100%; top:0px;left:0px;background-color: cornsilk">
                            <a href="javascript:void(0)"><span>点击获取最新数据</span></a>
                        </div>
                        <div class="data-pane">

                        </div>
                    </div>

                    <div class="tab-pane config" id="labr_config">
                    </div>

                    <div class="tab-pane" id="labr_chart">
                        <div class="chart-interval">
                            <a class="btn red m5">5分钟</a><a class="btn h1">1小时</a>
                        </div>
                        <div class="charts">

                        </div>
                        <div class="charts-bar" style="height:80px">

                        </div>
                    </div>

                    <div class="tab-pane" id="labr_chart_energy">

                        <div class="charts-energy">

                        </div>

                    </div>

                    <div class="tab-pane" id="labr_alert">
                        <div class="alert-pane">

                        </div>
                    </div>

                </div>
            </div>
        </div>
	</div>
</div>
