<div class="row-fluid">
<div class="span4" file="tab1.phtml">
	<div class="portlet box blue tabbable" widget-class="HpicSummaryDevice">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i></div>
		</div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class=" active" id="hpic_devices">
                        <div class=" active" id="hpge_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
	</div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="WeatherSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">气象</i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class=" active" id="weather_devices">
                        <div class=" active" id="hpge_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>

                            <a href="#" class="btn green details">查看详情</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- 气溶胶 -->
<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="Bai9850SummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="">

                <div class="tab-content">

                    <div class=" active" id="environment_devices">
                        <div class=" active" id="hpge_devices">
                            <div class="panel">
                                <span class="label run label-success"></span>
                            </div>
                            <a href="#" class="btn green details">查看详情</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
</div>
