<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="hpic-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;高压电离室</i></div>
		</div>
		<div class="portlet-body" widget-class="HpicDevice" widget-id="hpic-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#hpic_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#hpic_data" data-toggle="tab">数据</a></li>
				</ul>
				<div class="tab-content">

					<div class="tab-pane active" id="hpic_data">
                        <div class="list-pane"></div>
					</div>

                    <div class="tab-pane" id="hpic_chart">
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
