<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="weather-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;气象站</i></div>
		</div>
		<div class="portlet-body" widget-class="WeatherDevice" widget-id="weather-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#weather_config" data-toggle="tab">设置</a></li>
                    <li class="'dropdown">
                        <a href="#weather_alert" data-toggle="tab" class="dropdown-toggle" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li><a href="#weather_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#weather_data" data-toggle="tab">数据</a></li>
				</ul>
				<div class="tab-content">

                    <div class="tab-pane active" id="weather_data">
                        <div class="data-pane">

                        </div>
                    </div>

					<div class="tab-pane" id="weather_chart">
                        <div class="charts">

                        </div>
                        <div class="charts2">

                        </div>
					</div>
                    <div class="tab-pane config" id="weather_config">

                    </div>
                    <div class="tab-pane" id="weather_alert">
                        <div class="alert-pane">

                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
