<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="environment-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;环境与安防监控</i></div>
		</div>
		<div class="portlet-body" widget-class="EnvironmentDevice" widget-id="environment-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#environment_alert" data-toggle="tab">报警</a></li>
                    <li><a href="#environment_chart" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#environment_data" data-toggle="tab">数据</a></li>
				</ul>
				<div class="tab-content">

                    <div class="tab-pane active" id="environment_data">
                    </div>

					<div class="tab-pane" id="environment_chart">
					</div>

                    <div class="tab-pane" id="environment_alert">
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
