<div class="row-fluid">
<!-- Cinderella -->
<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="CinderellaSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i><span class="label label-success"></span></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#cinderella_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="cinderella_devices">
                        <a href="#" class="btn green details">查看数据</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="HpGeSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i><span class="label label-success"></span></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#hpge_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="hpge_devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="LabrSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i><span class="label label-success"></span></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#labr_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="labr_devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>

                    <!--
                    <div class="tab-pane" id="labr_settings">
                        <a href="#" class="btn green change-alert">确定</a>
                    </div>
                    -->
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
</div>
<!------------------------------- Line 2 --------------------------------->
<!-- ---高压电离室--->
<div class="row-fluid">
<div class="span4" file="tab1.phtml">
	<div class="portlet box blue tabbable" widget-class="HpicSummaryDevice">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i><span class="label label-success"></span></div>
		</div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#hpic_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="hpic_devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>
                    
                </div>
            </div>
        </div>
	</div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="WeatherSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">气象</i><span class="label label-success"></span></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#weather_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="weather_devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 环境与安防监控 -->
<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="EnvSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i><span class="label label-success"></span></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#environment_devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="environment_devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
</div>
