<div class="span12" file="tab1.phtml" widget-class="DeviceTabPane" widget-id="hpic-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">&nbsp;高压电离室</i></div>
		</div>
		<div class="portlet-body" widget-class="HpicDevice" widget-id="hpic-device">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#hpic_history" data-toggle="tab" class="history">获取率</a></li>
                    <li><a href="#hpic_config" data-toggle="tab">设置</a></li>
                    <li class="dropdown">

                        <a id="hpic_alert_a" href="#hpic_alert" data-toggle="tab" class="dropdown-toggle alerts" style="margin-top:6px;padding-top:8px;padding-bottom:8px">
                            <!-- <i class="icon-warning-sign"></i> -->
                            <span>报警&nbsp;</span>
                            <span class="badge" style="position: relative;top:0px;right:5px;-webkit-border-radius: 12px !important;background: red">0</span>
                        </a>
                    </li>
                    <li><a href="#hpic_chart" class="charts" data-toggle="tab">曲线</a></li>
                    <li class="active"><a href="#hpic_data" class="data" data-toggle="tab">数据</a></li>
				</ul>
				<div class="tab-content" style="position:relative;">

					<div class="tab-pane active" id="hpic_data">
                        <div class="refresh-bar" style="position:absolute;display: none; height: 24px;width: 100%; top:0px;left:0px;background-color: cornsilk">
                            <a href="javascript:void(0)"><span>点击获取最新数据</span></a>
                        </div>
                        <div class="interval" style="margin-bottom: 10px">
                            <a class="btn red mini s30">30秒</a> <a class="btn mini m5">5分钟</a> <a class="btn mini h1">1小时</a> <a class="btn mini d1">1天</a>

                            <a class="btn blue mini export exp_m5">导出5分钟均值数据</a>
                            <a class="btn blue mini export exp_h1">导出1小时均值数据</a>
                            <a class="btn blue mini export exp_d1">导出日均值数据</a>

                        </div>

                        <div class="data-pane">

                        </div>
					</div>

                    <div class="tab-pane" id="hpic_chart">
                        <div class="chart-interval">
                            <a class="btn mini s30">30秒</a> <a class="btn red mini m5">5分钟</a> <a class="btn mini h1">1小时</a> <a class="btn mini d1">1天</a>
                        </div>
                        <div class="charts">

                        </div>
                        <div class="charts-bar" style="height: 80px">

                        </div>
                    </div>
                    <div class="tab-pane config" id="hpic_config">
                    </div>
                    <div class="tab-pane" id="hpic_alert">
                        <select style="margin-bottom: 0px" class="alert-select">
                            <option value="1">一级报警</option>
                            <option value="2">二级报警</option>
                        </select>
                        <a class="btn blue handle">处理报警</a>
                        <div class="alert-pane">

                        </div>
                    </div>

                    <div class="tab-pane" id="hpic_history">
                        <div class="calendar-container" class="fc-ltr fc">
                        </div>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
