<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->

<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->

<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->

<head>

	<meta charset="utf-8" />
	<base href="/" />
	<title>北京市辐射环境监测系统 | 登录</title>

	<meta content="width=device-width, initial-scale=1.0" name="viewport" />

	<meta content="" name="description" />

	<meta content="" name="author" />

	<!-- BEGIN GLOBAL MANDATORY STYLES -->

	<link href="media/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/style-metro.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/style.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/style-responsive.css" rel="stylesheet" type="text/css"/>

	<link href="media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>

	<link href="media/css/uniform.default.css" rel="stylesheet" type="text/css"/>

	<!-- END GLOBAL MANDATORY STYLES -->

	<!-- BEGIN PAGE LEVEL STYLES -->

	<link href="media/css/lock.css" rel="stylesheet" type="text/css"/>

	<!-- END PAGE LEVEL STYLES -->

	<link rel="shortcut icon" href="media/image/favicon.ico" />

</head>

<!-- END HEAD -->

<!-- BEGIN BODY -->

<body>
    <DIV class="brand" STYLE="height: 70px;background-color: #FFFFFF">
        <a>
            <img src="media/image/huanbao_logo2.png" style="width: 60px;height: 60px; margin-top: 15px; margin-left: 10px" alt="logo"/>
        </a>
        <span style="display:block; font-family:'微软雅黑'; font-weight: bold; font-size: 28px;color:#000000; margin-top: -40px; margin-left: 80px">北京市辐射环境监测系统</span>
    </DIV>

	<div class="page-lock">

		<div class="page-logo">


            <!--
			<a class="brand" href="index.html">

			<img src="media/image/logo-big.png" alt="logo" />

			</a>
            -->
		</div>

		<div class="page-body">
			<div class="page-lock-info">

				<span style="font-size: 28px">登录</span>

				<form class="form-search">
					<div class="input-append">

						<input id="username" type="text" class="m-wrap" placeholder="用户名">
                        <!--
						<button class="btn blue icn-only signin"><i class="m-icon-swapright m-icon-white"></i></button>
                        -->
					</div>

                    <div style="height: 40px"></div>

					<div class="input-append">

						<input id="password" type="password" class="m-wrap" placeholder="密码">
                        <!--
                        <button class="btn blue icn-only signin"><i class="m-icon-swapright m-icon-white"></i></button>
                        -->
                    </div>

                    <div class="relogin" style="margin-top: 40px">
                        <!--
                        <a href="login.html">忘记密码</a>
                        -->
                        <span id='error' style="font-size: 14px;color: red"></span>
                        <a type="submit" class="btn blue signin">&nbsp;登录&nbsp;</a>
					</div>

				</form>

			</div>

		</div>



	</div>

	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

	<!-- BEGIN CORE PLUGINS -->

	<script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>

	<script src="media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->

	<script src="media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      

	<script src="media/js/bootstrap.min.js" type="text/javascript"></script>

	<!--[if lt IE 9]>

	<script src="media/js/excanvas.min.js"></script>

	<script src="media/js/respond.min.js"></script>  

	<![endif]-->   

	<script src="media/js/jquery.slimscroll.min.js" type="text/javascript"></script>

	<script src="media/js/jquery.blockui.min.js" type="text/javascript"></script>  

	<script src="media/js/jquery.cookie.min.js" type="text/javascript"></script>

	<script src="media/js/jquery.uniform.min.js" type="text/javascript" ></script>
    <script src="media/js/md5.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->

	<!-- BEGIN PAGE LEVEL PLUGINS -->

	<script src="media/js/jquery.backstretch.min.js" type="text/javascript"></script>

	<!-- END PAGE LEVEL PLUGINS -->   

	<script src="media/js/app.js"></script>  

	<script src="media/js/lock.js"></script>      

	<script>

        $(function() {

            App.init();
            Lock.init();


            $('a.signin').bind('click', function(){

                var username = $('#username').val();
                var password = hex_md5($('#password').val());

                $.ajax({
                    type: "POST",
                    url: "user/signIn",
                    data: {username:username, password:password},

                    success: function(data){
                        var d = eval("(" + data + ")")
                        if(d.errorCode == 0){
                            location.href = "/main";
                        } else
                        {
                            $('#error').text('用户名或密码错误');
                        }
                    }

                });

                return false;
            })

        });

	</script>
<!-- END JAVASCRIPTS -->
<!-- END BODY -->

</html>