<div class="span12" file="tab1.phtml">
    <div class="portlet box blue tabbable">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">&nbsp;GIS</i></div>
        </div>
        <div class="portlet-body" widget-class="BaiduMap" widget-id="map-id">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">

                    <li class="active"><a href="#" data-toggle="tab">GIS</a></li>

                </ul>
                <div class="tab-content">

                    <div class="tab-pane active">
                        <div class="map" id="allmap" style="width: 100%;height: 600px">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
