<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
<script src="media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="media/js/highcharts.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
<script src="media/js/bootstrap.min.js" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="media/js/excanvas.min.js"></script>
<script src="media/js/respond.min.js"></script>  
<![endif]-->   
<script src="media/js/jquery.slimscroll.min.js" type="text/javascript"></script>

<script src="media/js/jquery.blockui.min.js" type="text/javascript"></script>  
<script src="media/js/jquery.cookie.min.js" type="text/javascript"></script>
<script src="media/js/jquery.uniform.min.js" type="text/javascript" ></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!--
<script src="media/js/jquery.vmap.js" type="text/javascript"></script>   

<script src="media/js/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.world.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.usa.js" type="text/javascript"></script>

<script src="media/js/jquery.vmap.sampledata.js" type="text/javascript"></script>  
-->
<script src="media/js/jquery.flot.js" type="text/javascript"></script>
<script src="media/js/jquery.flot.resize.js" type="text/javascript"></script>
<script src="media/js/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="media/js/date.js" type="text/javascript"></script>
<script src="media/js/daterangepicker.js" type="text/javascript"></script>     
<script src="media/js/jquery.gritter.js" type="text/javascript"></script>
<script src="media/js/fullcalendar.min.js" type="text/javascript"></script>
<script src="media/js/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script src="media/js/jquery.sparkline.min.js" type="text/javascript"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="media/js/app.js" type="text/javascript"></script>
<script src="media/js/index.js" type="text/javascript"></script>
<script src="media/js/md5.js" type="text/javascript"></script>

<script src="media/js/jquery.backstretch.min.js" type="text/javascript"></script>
<script src="media/js/lock.js"></script>

<script src="active-web/config.js" type="text/javascript"></script>
<script src="active-web/classes.js" type="text/javascript"></script>

<!-- WIDGETS -->
<script src="media/widgets/Global.js" type="text/javascript"></script>
<script src="media/widgets/charts.js" type="text/javascript"></script>
<script src="media/widgets/HistoryPane.js" type="text/javascript"></script>
<script src="media/widgets/ListView.js" type="text/javascript"></script>
<script src="media/widgets/Breadcrumb.js" type="text/javascript"></script>
<script src="media/widgets/sidebar.js" type="text/javascript"></script>
<script src="media/widgets/pagebar.js" type="text/javascript"></script>
<script src="media/widgets/DeviceTabPane.js" type="text/javascript"></script>
<!-- Devices -->
<script src="media/widgets/HpicDevice.js" type="text/javascript"></script>
<script src="media/widgets/WeatherDevice.js" type="text/javascript"></script>
<script src="media/widgets/CinderellaDevice.js" type="text/javascript"></script>
<script src="media/widgets/LabrDevice.js" type="text/javascript"></script>
<script src="media/widgets/EnvDevice.js" type="text/javascript"></script>
<script src="media/widgets/HpgeDevice.js" type="text/javascript"></script>


<script src="media/widgets/DeviceSummary.js" type="text/javascript"></script>

<script src="media/widgets/StationTabPane.js" type="text/javascript"></script>
<script src="media/widgets/AdminManagerPane.js" type="text/javascript"></script>
<!-- WIDGETS -->
<!-- END PAGE LEVEL SCRIPTS -->  
<script>
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        Index.init();

        //Index.initJQVMAP();   // init index page's custom scripts
        Index.initCalendar();   // init index page's custom scripts
        Index.initCharts();     // init index page's custom scripts
        Index.initChat();
        Index.initMiniCharts();
        Index.initDashboardDaterange();
        Index.initIntro();

        Lock.init();

        /*
        var gr = new GroupValue({'time': "222"});
        gr.addValue({'a':5, 'time':"111", 'b':1.6});
        gr.addValue({'a':3, 'b':1.8,'time':"222"});
        gr.addValue({'a':5, 'b':2.8, 'time':"444"});

        var f = gr.getValue();
        */



        $.ajax({
            type: "GET",
            url: "user/test",
            data: null,
            success: function(data){
                var d = eval("(" + data + ")")
                if(d.errorCode == 201){
                    location.href = "/main/lock";
                } else {
                    $('body').css('display', '')
                }
            }
        });


        $('#signOut').bind('click', function(){
            $.ajax({
                type: "GET",
                url: "user/signOut",
                data: {},

                success: function(data){
                    var d = eval("(" + data + ")")
                    if(d.errorCode == 0){
                        location.href = "/main/lock";
                    }
                }

            });
        });



        g = new Global();
        activeWeb();


        g.init();
        g.addRow("#station-row");
        g.addRow("#devices-row");
        g.addRow("#admin-row");


        g.showRow("#station-row");


        setInterval(function(){
            // header_notification_bar
            $.ajax({
                type: "GET",
                url: "alert/count",
                data: {},

                success: function(data){
                    var d = eval("(" + data + ")")
                    if(d.errorCode == 0){
                        g.setAlerts(d.results);

                        // $('#header_notification_bar span.badge').text(d.results.count)

                        $('#hpic_alert_a span.badge').text(d.results.hpic);
                        $('#weather_alert_a span.badge').text(d.results.weather);
                        $('#labr_alert_a span.badge').text(d.results.labr);
                        $('#hpge_alert_a span.badge').text(d.results.hpge);
                        $('#cinderella_alert_a span.badge').text(d.results.cinderella);
                        $('#environment_alert_a span.badge').text(d.results.environment);

                    }
                }

            });
        }, 10 * 1000);


    });
</script>
<!-- END JAVASCRIPTS -->
