<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
<script src="media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="media/js/highcharts.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
<script src="media/js/bootstrap.min.js" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="media/js/excanvas.min.js"></script>
<script src="media/js/respond.min.js"></script>  
<![endif]-->   
<script src="media/js/jquery.slimscroll.min.js" type="text/javascript"></script>

<script src="media/js/jquery.blockui.min.js" type="text/javascript"></script>  
<script src="media/js/jquery.cookie.min.js" type="text/javascript"></script>
<script src="media/js/jquery.uniform.min.js" type="text/javascript" ></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!--
<script src="media/js/jquery.vmap.js" type="text/javascript"></script>   

<script src="media/js/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.world.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="media/js/jquery.vmap.usa.js" type="text/javascript"></script>

<script src="media/js/jquery.vmap.sampledata.js" type="text/javascript"></script>  
-->
<script src="media/js/jquery.flot.js" type="text/javascript"></script>
<script src="media/js/jquery.flot.resize.js" type="text/javascript"></script>
<script src="media/js/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="media/js/date.js" type="text/javascript"></script>
<script src="media/js/daterangepicker.js" type="text/javascript"></script>     
<script src="media/js/jquery.gritter.js" type="text/javascript"></script>
<script src="media/js/fullcalendar.min.js" type="text/javascript"></script>
<script src="media/js/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script src="media/js/jquery.sparkline.min.js" type="text/javascript"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="media/js/app.js" type="text/javascript"></script>
<script src="media/js/index.js" type="text/javascript"></script>
<script src="media/js/md5.js" type="text/javascript"></script>

<script src="media/js/jquery.backstretch.min.js" type="text/javascript"></script>
<script src="media/js/lock.js"></script>

<script src="active-web/config.js" type="text/javascript"></script>
<script src="active-web/classes.js" type="text/javascript"></script>

<!-- WIDGETS -->
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=DAzZndwrXhf73lVsRqQrkch6"></script>
<script type="text/javascript" src="http://developer.baidu.com/map/jsdemo/demo/convertor.js"></script>


<script src="media/widgets/Global.js" type="text/javascript"></script>
<script src="media/widgets/charts.js" type="text/javascript"></script>
<script src="media/widgets/MapWidget.js" type="text/javascript"></script>
<script src="media/widgets/HistoryPane.js" type="text/javascript"></script>
<script src="media/widgets/ListView.js" type="text/javascript"></script>
<script src="media/widgets/Breadcrumb.js" type="text/javascript"></script>
<script src="media/widgets/sidebar.js" type="text/javascript"></script>
<script src="media/widgets/pagebar.js" type="text/javascript"></script>
<script src="media/widgets/DeviceTabPane.js" type="text/javascript"></script>

<!-- Devices summary -->
<script src="media/widgets/DeviceSummary.js" type="text/javascript"></script>
<!-- 7 Devices -->
<script src="media/widgets/HpicDevice.js" type="text/javascript"></script>
<script src="media/widgets/WeatherDevice.js" type="text/javascript"></script>
<script src="media/widgets/CinderellaDevice.js" type="text/javascript"></script>
<script src="media/widgets/LabrDevice.js" type="text/javascript"></script>
<script src="media/widgets/HpgeDevice.js" type="text/javascript"></script>
<script src="media/widgets/EnvDevice.js" type="text/javascript"></script>
<script src="media/widgets/LabrFilterDevice.js" type="text/javascript"></script>
<script src="media/widgets/Bai9850Device.js" type="text/javascript"></script>
<script src="media/widgets/StationTabPane.js" type="text/javascript"></script>
<script src="media/widgets/AdminManagerPane.js" type="text/javascript"></script>
<script src="media/widgets/AdminSMPane.js" type="text/javascript"></script>
<!-- WIDGETS -->
<!-- END PAGE LEVEL SCRIPTS -->  
<script>
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        Index.init();

        //Index.initJQVMAP();   // init index page's custom scripts
        Index.initCalendar();   // init index page's custom scripts
        Index.initCharts();     // init index page's custom scripts
        Index.initChat();
        Index.initMiniCharts();
        Index.initDashboardDaterange();
        Index.initIntro();

        Lock.init();

        /*
        var gr = new GroupValue({'time': "222"});
        gr.addValue({'a':5, 'time':"111", 'b':1.6});
        gr.addValue({'a':3, 'b':1.8,'time':"222"});
        gr.addValue({'a':5, 'b':2.8, 'time':"444"});

        var f = gr.getValue();
        */

        $.ajax({
            type: "GET",
            url: "user/test",
            data: null,
            success: function(data){
                var d = eval("(" + data + ")")
                console.log(data)
                if(d.errorCode == 201){

                    location.href = "/main/lock";
                } else {
                    var url = window.location.href;
                    if (url.indexOf('hpge') > 0)
                    {
                        g.showRow("#devices-row");
                        var sid = url.substr(url.indexOf('hpge/') + 5);
                        DeviceSummaryBase.showDevice('hpge', sid);
                        setTimeout(function(){
                            $('body').css('display', '');
                            g.showRow("#devices-row");
                        }, 500);
                    }
                    else
                    {
                        $('body').css('display', '');
                        g.showRow("#station-129-row");
                    }
                }
            }
        });

        $('#signOut').bind('click', function(){
            $.ajax({
                type: "GET",
                url: "user/signOut",
                data: {},

                success: function(data){
                    var d = eval("(" + data + ")");
                    if(d.errorCode == 0){
                        location.href = "/main/lock";
                    }
                }

            });
        });

        g = new Global();
        g.init();
        g.setCurrentStationId(129);

        activeWeb();

        g.addRow("#station-129-row");
        g.addRow("#devices-row");
        g.addRow("#admin-row");
        g.addRow("#admin-sm-row");



        jQuery.download = function(url, data, method){
            // 获取url和data
            if( url && data ){
                // data 是 string 或者 array/object
                data = typeof data == 'string' ? data : jQuery.param(data);
                // 把参数组装成 form的 input
                var inputs = '';
                jQuery.each(data.split('&'), function(){
                    var pair = this.split('=');
                    inputs+='<input type="hidden" name="'+ pair[0] +'" value="'+ pair[1] +'" />';
                });
                // request发送请求
                jQuery('<form action="'+ url +'" method="'+ (method||'post') +'">'+inputs+'</form>')
                    .appendTo('body').submit().remove();
            };
        };


        // TODO: Move to each station-devices;

        setInterval(function(){
            // header_notification_bar
            $.ajax({
                type: "GET",
                url: "alert/count",
                data: {},


                success: function(data){
                    console.log(data);
                    var d = eval("(" + data + ")")
                    if(d.errorCode == 0){
                        g.setAlerts(d.results);

                        $('#hpic_alert_a span.badge').text(d.results.hpic);
                        //$('#weather_alert_a span.badge').text(d.results.weather);
                        //$('#labr_alert_a span.badge').text(d.results.labr);
                        $('#hpge_alert_a span.badge').text(d.results.hpge);
                        $('#cinderella_alert_a span.badge').text(d.results.cinderella);
                        $('#environment_alert_a span.badge').text(d.results.environment);
                        //$('#labrfilter_alert_a span.badge').text(d.results.labrfilter);

                    }
                }

            });
        }, 10 * 1000);


    });
</script>
<!-- END JAVASCRIPTS -->
