<!-- sidebar.phtml -->
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar nav-collapse collapse">
	<!-- BEGIN SIDEBAR MENU -->        
	<ul class="page-sidebar-menu">
		<li>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<div class="sidebar-toggler hidden-phone"></div>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
		</li>

		<li class="start active">
			<a href="index.html">
			<i class="icon-home"></i> 
			<span class="title">监测网络</span>
			<span class="selected"></span>
			</a>
			<ul class="sub-menu">
				<li>
					<a href="#report-secret-row">北京顺义站</a>
				</li>
				<li >
					<a href="#report-comment-row">北京昌平站</a>
				</li>

			</ul>			
		</li>

		<!-- 运营 -->
		<li class="start">
			<a href="index.html">
			<i class="icon-home"></i> 
			<span class="title">数据分析</span>
			<span class="selected"></span>
			</a>
			<ul class="sub-menu">
				<li>
					<a href="#add-secret-row">数据比较</a>
				</li>
			</ul>			
		</li>

        <!-- 管理 -->
        <li class="start">
            <a href="index.html">
                <i class="icon-home"></i>
                <span class="title">管理</span>
                <span class="selected"></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="#admin-man-row">账号管理</a>
                </li>
                <li>
                    <a href="#admin-man-row">自动站管理</a>
                </li>

            </ul>
        </li>
		
	</ul>
	<!-- END SIDEBAR MENU -->
</div>
<!-- END SIDEBAR -->