<!-- First line -->
<div class="row-fluid">
<div class="span6" file="tab1.phtml">
	<div class="portlet box blue tabbable" widget-class="HpicSummaryDevice">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder">高压电离室</i></div>
		</div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>

                    
                </div>
            </div>
        </div>
	</div>
</div>

<div class="span6" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="HpGeSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">高纯锗谱仪</i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
</div>

<!-- 第二行 -->
<div class="row-fluid">
<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="WeatherSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">气象</i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="LabrSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">Labr谱仪</i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

<div class="span4" file="tab1.phtml">
    <div class="portlet box blue tabbable" widget-class="EnvSummaryDevice">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder">环境与安防监控</i></div>
        </div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备简介</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <a href="#" class="btn green details">查看数据</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
</div>