<div class="span12" file="tab1.phtml" widget-class="StationTabPane" widget-id="station-tab-pane">
	<div class="portlet box green tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i></div>
		</div>
        <div class="portlet-body" widget-class="">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <!--
                    <li><a href="#hpic_chart" data-toggle="tab">自动站</a></li>
                    -->
                    <li class="active"><a href="#devices" data-toggle="tab">设备列表</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="devices">
                        <div class="list-pane"></div>
                    </div>

                    
                </div>
            </div>
        </div>
	</div>
</div>
