<div class="span12" file="tab1.phtml" widget-class="StationTabPane" widget-id="station-tab-pane" station_id="128">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder station"> 超大流量大气辐射环境自动监测站<span class="offline"></span></i></div>
		</div>
        <div class="portlet-body" >
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">

                    <li class="active!"><a href="#station_status_container" data-toggle="tab">状态</a></li>
                    <li class="active"><a href="#station_container_128" data-toggle="tab">简介</a></li>

                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="station_container_128">
                        <div style="float: left" class="span8">
                            <?php $this->partial("index/devices128"); ?>
                            <div class="clearfix"></div>
                        </div>

                        <div style="float: left">
                            <span></span>
                            <img src="/media/image/background.png"  style="height: 280px;float:right"/>

                        </div>
                    </div>

                    <div class="tab-pane" id="station_status_container">
                        <div class="">
                            <span>网络连接历史状态</span>
                        </div>
                        <div class="conn-alert-list">

                        </div>
                    </div>

                </div>
            </div>
        </div>
	</div>
</div>
